### PR TITLE
Add training snapshots

### LINKED ISSUE #5: Unable to train openmp model
There is some bug. I can compile but cannot run `./a.out`.

Maybe some small path parameter or some error.

@ayush5588 can you look into and verify it locally once.

### PR DESCRIPTION
**Pull request by ayush5588**
1. Training

2. Testing

Closes #5

### CODE REVIEW

**Review by oke-aditya — DISMISSED** [review]
LGTM

**Comment by oke-aditya** [comment]
Can you create a folder called images and attach these and push them too ? @ayush5588

**Comment by oke-aditya** [comment]
This will stay as some outputs which we can use later

**Review by oke-aditya — CHANGES_REQUESTED** [review]
Please add these images to a folder called `outputs`

**Comment by ayush5588** [comment]
> Please add these images to a folder called `outputs`

@oke-aditya yeah sure

**Comment by ayush5588** [comment]
> > Please add these images to a folder called `outputs`
> 
> @oke-aditya yeah sure

@oke-aditya Please check i have done that

**Comment by oke-aditya** [comment]
You can simply re request review to trigger such stuff 😀 anyways

**Review by oke-aditya — APPROVED** [review]

**Pull request merged**
